package de.saltyfearz.saltyskies.enums;

public enum LUMBERJACK_BLOCKS {

    OAK_LOG,
    STRIPPED_OAK_LOG,
    ACACIA_LOG,
    STRIPPED_ACACIA_LOG,
    BIRCH_LOG,
    STRIPPED_BIRCH_LOG,
    DARK_OAK_LOG,
    STRIPPED_DARK_OAK_LOG,
    JUNGLE_LOG,
    STRIPPED_JUNGLE_LOG,
    SPRUCE_LOG,
    STRIPPED_SPRUCE_LOG,
    ACACIA_SAPLING,
    BIRCH_SAPLING,
    OAK_SAPLING,
    DARK_OAK_SAPLING,
    JUNGLE_SAPLING,
    SPRUCE_SAPLING

}
