package de.saltyfearz.saltyskies.enums;

public enum MINING_BLOCKS {

    NETHER_QUARTZ_ORE,
    DIAMOND_ORE,
    GOLD_ORE,
    COAL_ORE,
    IRON_ORE,
    EMERALD_ORE,
    REDSTONE_ORE,
    NETHER_GOLD_ORE,
    LAPIS_ORE,
    ANCIENT_DEBRIS,

    STONE,
    COBBLESTONE,

    MOSSY_COBBLESTONE,

    ANDESITE,
    DIORITE,
    GRANITE,

    OBSIDIAN,

    PRISMARINE,
    PRISMARINE_BRICKS,
    PRISMARINE_STAIRS,
    PRISMARINE_SLABS,
    DARK_PRISMARINE,
    DARK_PRISMARINE_SLAB,
    DARK_PRISMARINE_STAIRS,
    SEA_LANTERN,

    END_CRYSTAL,
    END_ROD,
    END_STONE,
    END_STONE_BRICKS,
    PURPUR_BLOCK,
    PURPUR_PILLAR,
    PURPUR_SLAB,
    PURPUR_STAIRS,

    GLOWSTONE,
    NETHER_BRICKS,
    NETHERRACK,

    GRINDSTONE,

    PACKED_ICE,

    RED_SANDSTONE,
    SANDSTONE,
    CUT_SANDSTONE,
    CHISELED_SANDSTONE
}
